### ISSUE TITLE
Dota 2 doesn't automatically create hero_grid_config.json

### ISSUE THREAD

**Issue by liamgold** [PederHA/odherogrid#2]
If you've never created a custom grid layout in Dota 2 before, then Dota 2 doesn't automatically create a hero_grid_config.json file in your steam userdata and you receive the following error when using odhg:

`Verify that the correct file path has been specified.`

Can odhg create the relevant json file automatically instead? I got around this by creating a custom grid layout in Dota 2 first, and then running odhg cmd line again.

**Comment by PederHA** [comment]
Sorry for the late response. Yeah, I'll make sure to add that ASAP.

**Comment by PederHA** [comment]
Fixed in f679066b1187930f96ed691916deb77fa7ee121b. 
New version is up on PyPi.
